"""
AI-powered Pull Request Review Step.

This step uses TAP (Titan Adapter Protocol) to enable autonomous AI agents
to review pull requests and provide feedback.
"""

from typing import List, Dict, Any
from titan_cli.engine import WorkflowContext, WorkflowResult, Success, Error
from ..exceptions import GitHubAPIError


def review_pr_step(ctx: WorkflowContext) -> WorkflowResult:
    """
    Reviews a GitHub pull request using AI.

    This step retrieves PR information and uses an AI agent with tools
    to analyze the changes, check for issues, and provide review comments.

    Context Args:
        pr_number (int): The pull request number to review.
        review_focus (str, optional): What to focus on (e.g., 'security', 'performance', 'style').
                                     Defaults to 'general'.
        auto_comment (bool, optional): Whether to post comments automatically. Defaults to False.

    Returns:
        WorkflowResult:
            - Success: If the review is completed, with 'review_summary' in metadata.
            - Error: If any required context arguments are missing or if the review fails.
    """
    # 1. Check dependencies
    if not ctx.github:
        return Error("GitHub client is not available in the workflow context.")

    if not ctx.ai:
        return Error("AI client is not available in the workflow context.")

    # 2. Get required data from context
    pr_number = ctx.get("pr_number")
    if not pr_number:
        return Error("Missing required context: pr_number")

    review_focus = ctx.get("review_focus", "general")
    auto_comment = ctx.get("auto_comment", False)

    try:
        # 3. Fetch PR information
        ctx.ui.text.info(f"Fetching PR #{pr_number} information...")
        pr_info = ctx.github.get_pull_request(pr_number)

        # 4. Fetch PR diff/changes
        ctx.ui.text.info("Analyzing PR changes...")
        pr_diff = ctx.github.get_pull_request_diff(pr_number)

        # 5. Create tools for the AI agent
        from ..tools import (
            GetPRFilesTool,
            GetPRCommentsTool,
            AnalyzeCodeTool,
            SuggestImprovementTool
        )

        tools = [
            GetPRFilesTool(ctx.github, pr_number),
            GetPRCommentsTool(ctx.github, pr_number),
            AnalyzeCodeTool(),
            SuggestImprovementTool()
        ]

        # 6. Create review prompt
        system_prompt = f"""You are an expert code reviewer.
Review focus: {review_focus}

Guidelines:
- Be constructive and helpful
- Identify potential bugs, security issues, and performance problems
- Suggest improvements for code quality and maintainability
- Check for best practices and coding standards
- Provide specific examples when suggesting changes
"""

        review_prompt = f"""
Please review Pull Request #{pr_number}: "{pr_info['title']}"

PR Description:
{pr_info['body']}

Number of files changed: {pr_info['changed_files']}
Additions: +{pr_info['additions']}, Deletions: -{pr_info['deletions']}

Analyze the changes and provide a comprehensive review. Use your tools to:
1. Get the list of changed files
2. Check existing comments
3. Analyze the code for issues
4. Suggest improvements

Provide a structured review with:
- Summary of changes
- Issues found (if any)
- Suggestions for improvement
- Overall assessment
"""

        # 7. Execute AI review using TAP
        ctx.ui.text.info("Running AI-powered code review...")

        response = ctx.ai.generate_with_tools(
            prompt=review_prompt,
            tools=tools,
            system_prompt=system_prompt,
            temperature=0.3  # Lower temperature for more focused analysis
        )

        # 8. Process review results
        review_summary = response['content']
        tools_used = [call['tool'] for call in response['tool_calls']]

        ctx.ui.text.success("AI review completed")
        ctx.ui.text.info(f"Tools used: {', '.join(set(tools_used))}")

        # 9. Optionally post review comment
        if auto_comment:
            ctx.ui.text.info("Posting review comment to PR...")
            comment_body = f"""## 🤖 AI Code Review

{review_summary}

---
*Generated by Titan CLI AI Agent using {len(response['tool_calls'])} tool calls in {response['iterations']} iterations*
"""
            ctx.github.create_pull_request_comment(
                pr_number=pr_number,
                body=comment_body
            )
            ctx.ui.text.success("Review comment posted")

        # 10. Return Success with review results
        return Success(
            f"Pull request #{pr_number} reviewed successfully.",
            metadata={
                "review_summary": review_summary,
                "tools_used": tools_used,
                "iterations": response['iterations'],
                "pr_number": pr_number,
                "auto_commented": auto_comment
            }
        )

    except GitHubAPIError as e:
        return Error(f"GitHub API error during review: {e}")
    except Exception as e:
        return Error(f"Unexpected error during AI review: {e}")


def analyze_pr_security_step(ctx: WorkflowContext) -> WorkflowResult:
    """
    Specialized step for security-focused PR analysis.

    This is a convenience wrapper around review_pr_step with security focus.

    Context Args:
        pr_number (int): The pull request number to review.
        auto_comment (bool, optional): Whether to post comments automatically. Defaults to False.

    Returns:
        WorkflowResult: Same as review_pr_step
    """
    # Set security focus
    ctx.data["review_focus"] = "security"

    return review_pr_step(ctx)


def analyze_pr_performance_step(ctx: WorkflowContext) -> WorkflowResult:
    """
    Specialized step for performance-focused PR analysis.

    This is a convenience wrapper around review_pr_step with performance focus.

    Context Args:
        pr_number (int): The pull request number to review.
        auto_comment (bool, optional): Whether to post comments automatically. Defaults to False.

    Returns:
        WorkflowResult: Same as review_pr_step
    """
    # Set performance focus
    ctx.data["review_focus"] = "performance"

    return review_pr_step(ctx)
