"""
AI Enhance Issue Description Step

Uses AI to enhance the brief description into a detailed issue description.
"""

from pathlib import Path
from jinja2 import Template
from titan_cli.engine import WorkflowContext, WorkflowResult, Success, Error, Skip
from titan_cli.ui.tui.widgets import Panel
from titan_plugin_jira.constants import (
    StepTitles,
    ErrorMessages,
    SuccessMessages,
    InfoMessages,
    AI_PROMPT_TEMPLATE,
    FALLBACK_ISSUE_TEMPLATE,
    DEFAULT_TITLE,
)


def ai_enhance_issue_description(ctx: WorkflowContext) -> WorkflowResult:
    """
    Use AI to generate title and enhance the brief description into a detailed description.

    Uses template from:
    1. Project: .titan/templates/issue_templates/default.md.j2
    2. Fallback: Plugin's default template

    Requires:
    - ctx.data["brief_description"]
    - ctx.data["issue_type"]

    Stores in:
    - ctx.data["title"] = str (generated by AI)
    - ctx.data["enhanced_description"] = str

    Returns:
        WorkflowResult
    """
    ctx.textual.begin_step(StepTitles.AI_GENERATE)

    # Get required data
    brief_description = ctx.data.get("brief_description")
    issue_type = ctx.data.get("issue_type")

    if not brief_description or not issue_type:
        ctx.textual.mount(Panel(ErrorMessages.MISSING_REQUIRED_DATA, panel_type="error"))
        ctx.textual.end_step("error")
        return Error("missing_required_data")

    ctx.textual.markdown("## 🤖 Generating Description with AI")
    ctx.textual.text("")
    ctx.textual.dim_text(InfoMessages.GENERATING_AI_DESC)
    ctx.textual.text("")

    # Check if AI is available
    if not ctx.ai:
        ctx.textual.mount(Panel(ErrorMessages.AI_NOT_AVAILABLE, panel_type="warning"))
        ctx.data["enhanced_description"] = brief_description
        ctx.data["title"] = DEFAULT_TITLE
        ctx.textual.end_step("skip")
        return Skip("ai_not_available")

    # Load template
    template_content = _load_template()

    # Build AI prompt
    prompt = AI_PROMPT_TEMPLATE.format(
        issue_type=issue_type, brief_description=brief_description
    )

    # Call AI
    with ctx.textual.loading("Generating description with AI..."):
        try:
            from titan_cli.ai.models import AIMessage

            messages = [AIMessage(role="user", content=prompt)]
            ai_response = ctx.ai.generate(messages)
            response = (
                ai_response.content
                if hasattr(ai_response, "content")
                else str(ai_response)
            )
        except Exception as e:
            ctx.textual.mount(
                Panel(ErrorMessages.AI_GENERATION_FAILED.format(error=str(e)), panel_type="error")
            )
            ctx.data["enhanced_description"] = brief_description
            ctx.data["title"] = DEFAULT_TITLE
            ctx.textual.end_step("error")
            return Error(f"ai_generation_failed: {e}")

    # Parse AI response
    parsed = _parse_ai_response(response)

    # Extract title
    title = parsed.pop("title", DEFAULT_TITLE)

    # Validate title length
    if len(title) > 255:
        title = title[:255]

    # Store title in context
    ctx.data["title"] = title

    # Render template
    try:
        template = Template(template_content)
        enhanced_description = template.render(**parsed)
    except Exception as e:
        ctx.textual.mount(
            Panel(ErrorMessages.TEMPLATE_RENDER_FAILED.format(error=str(e)), panel_type="error")
        )
        enhanced_description = response

    # Store in context
    ctx.data["enhanced_description"] = enhanced_description

    ctx.textual.success_text(SuccessMessages.TITLE_GENERATED.format(title=title))
    ctx.textual.success_text(SuccessMessages.DESCRIPTION_GENERATED)
    ctx.textual.text("")

    # Show preview
    ctx.textual.markdown(InfoMessages.PREVIEW_LABEL)
    ctx.textual.text("")
    preview = (
        enhanced_description[:500] + "..."
        if len(enhanced_description) > 500
        else enhanced_description
    )
    ctx.textual.markdown(preview)
    ctx.textual.text("")

    ctx.textual.end_step("success")

    return Success(
        "Title and description generated",
        metadata={"title": title, "description_length": len(enhanced_description)},
    )


def _load_template() -> str:
    """
    Load template from project or use default.

    Tries:
    1. .titan/templates/issue_templates/default.md.j2 (project)
    2. Plugin's default template

    Returns:
        Template content as string
    """
    # Try project template first
    project_template_path = Path(".titan/templates/issue_templates/default.md.j2")
    if project_template_path.exists():
        return project_template_path.read_text()

    # Use plugin default
    plugin_template_path = (
        Path(__file__).parent.parent / "config/templates/generic_issue.md.j2"
    )
    if plugin_template_path.exists():
        return plugin_template_path.read_text()

    # Ultimate fallback
    return FALLBACK_ISSUE_TEMPLATE


def _parse_ai_response(response: str) -> dict:
    """
    Parse AI response into template variables.

    Expected format:
    TITLE:
    ...
    DESCRIPTION:
    ...
    OBJECTIVE:
    ...
    ACCEPTANCE_CRITERIA:
    ...
    TECHNICAL_NOTES:
    ...
    DEPENDENCIES:
    ...

    Returns:
        Dict with template variables (including title)
    """
    sections = {
        "title": "",
        "description": "",
        "objective": "",
        "acceptance_criteria": "",
        "gherkin_tests": None,
        "technical_notes": None,
        "dependencies": None,
    }

    current_section = None
    lines = response.split("\n")

    for line in lines:
        line_upper = line.strip().upper()

        if line_upper.startswith("TITLE:"):
            current_section = "title"
            continue
        elif line_upper.startswith("DESCRIPTION:"):
            current_section = "description"
            continue
        elif line_upper.startswith("OBJECTIVE:"):
            current_section = "objective"
            continue
        elif line_upper.startswith("ACCEPTANCE_CRITERIA:"):
            current_section = "acceptance_criteria"
            continue
        elif line_upper.startswith("GHERKIN_TESTS:"):
            current_section = "gherkin_tests"
            sections["gherkin_tests"] = ""  # Initialize as empty string
            continue
        elif line_upper.startswith("TECHNICAL_NOTES:"):
            current_section = "technical_notes"
            sections["technical_notes"] = ""  # Initialize as empty string
            continue
        elif line_upper.startswith("DEPENDENCIES:"):
            current_section = "dependencies"
            sections["dependencies"] = ""  # Initialize as empty string
            continue

        if current_section:
            content = line.strip()
            if content and content.upper() != "N/A":
                if sections[current_section] is None:
                    sections[current_section] = ""
                sections[current_section] += content + "\n"

    # Clean up
    for key in sections:
        if sections[key]:
            sections[key] = sections[key].strip()
        if sections[key] == "":
            sections[key] = None

    return sections
