"""Default review profile definitions for GitHub code review."""

from ..models.review_enums import ChecklistCategory
from ..models.review_profile_models import (
    CandidateExclusions,
    CandidateScoringRule,
    ReviewAxisRule,
    ReviewProfile,
)


DEFAULT_REVIEW_PROFILE = ReviewProfile(
    version=1,
    change_patterns={
        "central_behavior": [
            "**/core/**",
            "**/services/**",
            "**/domain/**",
            "**/operations/**",
            "**/usecases/**",
            "**/utils/**",
            "**/middleware/**",
            "**/configuration/**",
        ],
        "entrypoint": [
            "**/main.py",
            "**/main.ts",
            "**/main.js",
            "**/*mainactivity*",
            "**/*cli.py",
            "**/routes/**",
            "**/controllers/**",
            "**/router*",
            "**/listener*",
            "**/dispatcher*",
        ],
        "repeated_callsite": [
            "**/components/**",
            "**/views/**",
            "**/screens/**",
            "**/dialogs/**",
            "**/*screen*",
            "**/*view*",
        ],
    },
    file_roles={
        "tests": ["**/test/**", "**/tests/**", "**/*test*", "**/*spec*"],
        "config_or_contracts": [
            "**/*config*",
            "**/*schema*",
            "**/*contract*",
            "**/*constants*",
            "**/*settings*",
            "**/*.yaml",
            "**/*.yml",
            "**/*.toml",
            "**/*.json",
        ],
        "workflow_orchestration": [
            "**/workflows/**",
            "**/steps/**",
            "**/step_registry/**",
            "**/*step_registry*",
            "**/*workflow*",
            "**/*step*",
            "**/*executor*",
            "**/*pipeline*",
            "**/*command*",
        ],
        "integration_or_adapter": [
            "**/clients/**",
            "**/adapters/**",
            "**/network/**",
            "**/api/**",
            "**/serializers/**",
            "**/parsers/**",
            "**/mappers/**",
            "**/*adapter*",
            "**/*client*",
            "**/*network*",
            "**/*api*",
            "**/*gateway*",
            "**/*serializer*",
            "**/*parser*",
            "**/*mapper*",
            "**/*converter*",
        ],
        "entrypoints_or_ui": [
            "**/screens/**",
            "**/views/**",
            "**/controllers/**",
            "**/routers/**",
            "**/*screen*",
            "**/*view*",
            "**/*activity*",
            "**/*controller*",
            "**/*cli*",
            "**/main.py",
            "**/main.ts",
            "**/main.js",
            "**/*mainactivity*",
            "**/*router*",
        ],
        "business_logic": [
            "**/services/**",
            "**/usecases/**",
            "**/operations/**",
            "**/core/**",
            "**/*service*",
            "**/*usecase*",
            "**/*operation*",
            "**/*manager*",
            "**/*logic*",
            "**/*core*",
            "**/*model*",
        ],
    },
    candidate_scoring=[
        CandidateScoringRule(
            name="domain_critical_path",
            patterns=[
                "**/*controller*",
                "**/*service*",
                "**/*store*",
                "**/*client*",
                "**/*handler*",
                "**/*validator*",
                "**/*middleware*",
                "**/*repository*",
                "**/*viewmodel*",
                "**/*presenter*",
                "**/*coordinator*",
                "**/*manager*",
                "**/*api*",
                "**/*router*",
                "**/*mapper*",
                "**/*serializer*",
                "**/*formatter*",
                "**/*adapter*",
                "**/*converter*",
                "**/*event*",
                "**/*classification*",
                "**/*normalizer*",
                "**/*parser*",
                "**/*model*",
            ],
            score_delta=4,
            reason="domain-critical path",
        ),
        CandidateScoringRule(
            name="semantic_mapping",
            patterns=[
                "**/*mapper*",
                "**/*serializer*",
                "**/*formatter*",
                "**/*adapter*",
                "**/*converter*",
                "**/*event*",
                "**/*classification*",
                "**/*normalizer*",
                "**/*parser*",
                "**/*model*",
            ],
            score_delta=3,
            reason="semantic mapping surface",
        ),
        CandidateScoringRule(
            name="security_sensitive",
            patterns=["**/*auth*", "**/*permission*", "**/*security*", "**/*payment*", "**/*billing*"],
            score_delta=5,
            reason="security or access-sensitive area",
        ),
        CandidateScoringRule(
            name="shared_helper",
            patterns=["**/*util*", "**/*interceptor*", "**/*configuration*", "**/*intent*"],
            score_delta=5,
            reason="shared helper or policy surface",
        ),
    ],
    candidate_exclusions=CandidateExclusions(
        low_signal_test_max_changes=20,
        low_signal_config_max_changes=10,
    ),
    review_axes={
        ChecklistCategory.FUNCTIONAL_CORRECTNESS: ReviewAxisRule(always_include=True),
        ChecklistCategory.ERROR_HANDLING: ReviewAxisRule(always_include=True),
        ChecklistCategory.SEMANTIC_CORRECTNESS: ReviewAxisRule(
            patterns=[
                "**/*mapper*",
                "**/*serializer*",
                "**/*formatter*",
                "**/*adapter*",
                "**/*converter*",
                "**/*event*",
                "**/*classification*",
                "**/*normalizer*",
                "**/*parser*",
                "**/*model*",
            ]
        ),
        ChecklistCategory.STATE_CONSISTENCY: ReviewAxisRule(
            patterns=[
                "**/*state*",
                "**/*result*",
                "**/*status*",
                "**/*callback*",
                "**/*listener*",
                "**/*event*",
                "**/*store*",
            ]
        ),
        ChecklistCategory.TEST_COVERAGE: ReviewAxisRule(patterns=["**/*test*", "**/*spec*"]),
        ChecklistCategory.API_CONTRACT: ReviewAxisRule(
            patterns=["**/*api*", "**/*schema*", "**/*model*", "**/*contract*"]
        ),
        ChecklistCategory.DATA_VALIDATION: ReviewAxisRule(
            patterns=["**/*validator*", "**/*request*", "**/*form*", "**/*serializer*"]
        ),
        ChecklistCategory.SECURITY: ReviewAxisRule(
            patterns=["**/*auth*", "**/*permission*", "**/*security*", "**/*payment*", "**/*billing*"]
        ),
    },
)
