config_version = "1.0"

[project]
name = "titan-cli"
type = "generic"

[plugins.git]
enabled = true

[plugins.git.config]
main_branch = "master"
default_remote = "origin"

[plugins.github]
enabled = true

[plugins.github.config]
repo_owner = "masorange"
repo_name = "titan-cli"
default_branch = "master"
pr_template_path = ".github/pull_request_template.md"
auto_assign_prs = true

[plugins.jira]
enabled = false

[plugins.slack]
enabled = true

[plugins.slack.config]
oauth_client_id = "6537700668563.11317707809587"
default_team_id = "T06FTLLKNGK"
default_team_name = "MasStack"
granted_scopes = [
    "identify",
    "channels:history",
    "groups:history",
    "im:history",
    "mpim:history",
    "channels:read",
    "groups:read",
    "users:read",
    "channels:write",
    "chat:write",
    "groups:write",
    "im:write",
    "mpim:write",
]
default_channels = ["titan-cli", "chapter-apps-general", "chapter-apps-ios-ragnarok", "chapter-apps-android-ragnarok"]
