"""
Titan CLI Operations

Pure business logic functions that can be used in steps or called programmatically.
All functions here are UI-agnostic and can be unit tested independently.
"""

from .ruff_operations import (
    parse_ruff_json_output,
    format_file_path,
    build_ruff_error_table_data,
    format_ruff_errors_for_ai,
)

from .pytest_operations import (
    parse_pytest_report_summary,
    build_failure_table_data,
    format_failures_for_ai,
    truncate_text,
)

from .log_operations import (
    LogFileInfo,
    LogEntry,
    SessionSegment,
    SessionRef,
    LogSession,
    WorkflowRun,
    StepRun,
    EntryGroup,
    SessionAnalysis,
    DEFAULT_LOG_DIR,
    DEFAULT_LOG_NAME,
    DEFAULT_REPORT_DIR,
    SLOW_THRESHOLD_SECONDS,
    ERROR_LEVELS,
    ENGINE_TIMELINE_EVENTS,
    STEP_RESULT_ICONS,
    STEP_RESULT_LEGEND,
    WORKFLOW_STATUS_ICONS,
    LEVEL_ICONS,
    discover_log_files,
    chronological_paths,
    index_sessions,
    load_session,
    analyze_session,
    group_entries,
    filter_entries,
    entries_around,
    workflow_names,
    entry_message,
    entry_context_fields,
    format_entry_json,
    to_local,
    format_time,
    format_duration,
    format_file_label,
    format_file_description,
    format_session_label,
    format_session_description,
    format_entry_line,
    build_session_evidence,
    build_diagnosis_prompt,
    build_report_document,
    default_report_path,
)

from .workflow_profile_operations import (
    ItemTable,
    Budget,
    StepProfile,
    FunnelPoint,
    WorkflowRunProfile,
    RunRef,
    WorkflowSummary,
    FunnelStage,
    Interpretation,
    INTERPRETERS,
    StepStats,
    RunHistory,
    profile_workflow_run,
    inventory_runs,
    load_run,
    summarize_workflows,
    format_run_choice,
    format_run_header,
    interpret_run,
    label_for,
    build_run_history,
    format_comparison,
    build_assessment_prompt,
)

from .plugin_docs_operations import (
    OFFICIAL_PLUGIN_REFS,
    build_all_plugin_inventories,
    build_plugin_inventory,
    extract_docstring_summary,
    inventory_output_path,
    parse_docstring_sections,
    render_plugin_inline_step_contracts_markdown,
    render_plugin_step_reference_markdown,
    step_reference_output_path,
    update_plugin_workflow_steps_pages,
    validate_generated_inventories,
    validate_generated_step_references,
    validate_workflow_steps_pages,
    write_plugin_inventories,
    write_plugin_step_references,
    workflow_steps_page_path,
)

__all__ = [
    # Ruff operations
    "parse_ruff_json_output",
    "format_file_path",
    "build_ruff_error_table_data",
    "format_ruff_errors_for_ai",

    # Pytest operations
    "parse_pytest_report_summary",
    "build_failure_table_data",
    "format_failures_for_ai",
    "truncate_text",

    # Log operations
    "LogFileInfo",
    "LogEntry",
    "SessionSegment",
    "SessionRef",
    "LogSession",
    "WorkflowRun",
    "StepRun",
    "EntryGroup",
    "SessionAnalysis",
    "DEFAULT_LOG_DIR",
    "DEFAULT_LOG_NAME",
    "DEFAULT_REPORT_DIR",
    "SLOW_THRESHOLD_SECONDS",
    "ERROR_LEVELS",
    "ENGINE_TIMELINE_EVENTS",
    "STEP_RESULT_ICONS",
    "STEP_RESULT_LEGEND",
    "WORKFLOW_STATUS_ICONS",
    "LEVEL_ICONS",
    "discover_log_files",
    "chronological_paths",
    "index_sessions",
    "load_session",
    "analyze_session",
    "group_entries",
    "filter_entries",
    "entries_around",
    "workflow_names",
    "entry_message",
    "entry_context_fields",
    "format_entry_json",
    "to_local",
    "format_time",
    "format_duration",
    "format_file_label",
    "format_file_description",
    "format_session_label",
    "format_session_description",
    "format_entry_line",
    "build_session_evidence",
    "build_diagnosis_prompt",
    "build_report_document",
    "default_report_path",

    # Workflow profiling
    "ItemTable",
    "Budget",
    "StepProfile",
    "FunnelPoint",
    "WorkflowRunProfile",
    "RunRef",
    "WorkflowSummary",
    "FunnelStage",
    "Interpretation",
    "INTERPRETERS",
    "StepStats",
    "RunHistory",
    "profile_workflow_run",
    "inventory_runs",
    "load_run",
    "summarize_workflows",
    "format_run_choice",
    "format_run_header",
    "interpret_run",
    "label_for",
    "build_run_history",
    "format_comparison",
    "build_assessment_prompt",

    # Plugin docs operations
    "OFFICIAL_PLUGIN_REFS",
    "build_all_plugin_inventories",
    "build_plugin_inventory",
    "extract_docstring_summary",
    "inventory_output_path",
    "parse_docstring_sections",
    "render_plugin_inline_step_contracts_markdown",
    "render_plugin_step_reference_markdown",
    "step_reference_output_path",
    "update_plugin_workflow_steps_pages",
    "validate_generated_inventories",
    "validate_generated_step_references",
    "validate_workflow_steps_pages",
    "write_plugin_inventories",
    "write_plugin_step_references",
    "workflow_steps_page_path",
]
