name: Protect workflows folder

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  protect:
    uses: masorange/masorange-gh-actions/.github/workflows/protect-workflows-folder.yml@master
    secrets:
      ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
